global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@facerecognition.local'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: face-recognition
      receiver: 'face-recognition-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@facerecognition.local'
    # Slack notifications (configure with your webhook URL)
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#alerts'
    #     title: 'Critical Alert: Face Recognition System'
    #     text: |
    #       {{ range .Alerts }}
    #       *Alert:* {{ .Annotations.summary }}
    #       *Description:* {{ .Annotations.description }}
    #       *Severity:* {{ .Labels.severity }}
    #       {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@facerecognition.local'

  - name: 'face-recognition-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/face-recognition-webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert_user'
            password: 'alert_password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

